spring:
  h2.console.enabled: true
  datasource:
    url: 'jdbc:h2:~/test'
    username: 'sa'
    hikari:
      maximum-pool-size: 2
  jpa.properties.hibernate.dialect: 'org.hibernate.dialect.H2Dialect'

server:
  port: 8081