version: "3"
services:
  web:
    image: docker-swarm-troobleshoot-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:9080"
  db:
    image: mongo
    ports:
      - "27017:27017"
