version: "3"
services:
  kafka:
    image: 'bitnami/kafka:2.0.0'
    expose:
      - "9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
  zookeeper:
    image: 'bitnami/zookeeper:3.4.12'
    expose:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes